baseURL = "http://example.org/"
languageCode = "es"
title = "Comida de otra Galaxia"
theme = "tale"

[menu]
    [[menu.main]]
        identifier = "Comida Chatarra"
        name = "Comida Chatarra"
        title = "Comida Chatarra"
        url  = "content/posts/ComidaChatarra/"
        weight = 0

    [[menu.main]]
        identifier = "Comida Baby Yoda"
        name = "Comida Baby Yoda"
        title = "Comida Baby Yoda"
        url  = "/posts/"
        weight = 0

    [[menu.main]]
        identifier = "Comida Vegana Intergal치ctica"
        name = "Comida Vegana Intergal치ctica"
        title = "Comida Vegana Intergal치ctica"
        url  = "Comida Vegana Intergal치ctica.md"
        weight = 0