  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Comida Vegana Intergalactica"
  weight = 200
  identifier = "Comida Vegana Intergalactica"
  url = "/ComidaVeganaIntergalactica/"

  [[main]]
  name = "Comida Chatarra"
  weight = 300
  identifier = "Comida Chatarra"
  url = "/ComidaChatarra/"

  [[main]]
  name = "Comida Baby Yoda"
  weight = 300
  identifier = "Comida Baby Yoda"
  url = "/ComidaBabyYoda/"

  [[main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"